site_name: Languru
repo_url: https://github.com/dockhardman/languru
repo_name: dockhardman/languru
edit_uri: edit/master/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  palette:
    - primary: lime
    - accent: lime
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.path
    - navigation.tabs
    - navigation.top
    - toc.follow
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "mermaid"
plugins:
  - git-authors
  - mkdocs-nav-weight
  - neoteroi.mkdocsoad
  - search
  - tags
  - git-committers:
      repository: dockhardman/languru
      branch: master
  - git-revision-date-localized:
      enable_creation_date: true
  - render_swagger:
      allow_arbitrary_locations: true
